import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { Drawing } from './drawing.entity';

/**
 * Reference Type Enum
 *
 * Types of references between drawings common in construction documentation
 */
export enum ReferenceType {
  DETAIL = 'detail',
  SECTION = 'section',
  ELEVATION = 'elevation',
  PLAN = 'plan',
  SCHEDULE = 'schedule',
  ENLARGED_PLAN = 'enlarged_plan',
  REFLECTED_CEILING = 'reflected_ceiling',
  OTHER = 'other',
}

/**
 * Drawing Cross-Reference Entity
 *
 * Tracks references between drawings (e.g., "See A-501 for wall section detail").
 * Maintains bidirectional relationships between drawings for navigation.
 *
 * Features:
 * - Source/target drawing relationships
 * - Reference type classification
 * - Callout/marker text (e.g., "3/A-501")
 * - Description and notes
 * - Grid location context
 * - Automatic bidirectional tracking
 *
 * Examples:
 * - Floor plan (A-101) references wall section detail on A-501
 * - Section drawing (S-201) references foundation detail on S-101
 * - Enlarged plan (A-201.1) references main floor plan A-201
 *
 * @entity drawing_cross_references
 */
@Entity('drawing_cross_references')
@Index('IDX_cross_ref_source', ['sourceDrawingId'])
@Index('IDX_cross_ref_target', ['targetDrawingId'])
@Index('IDX_cross_ref_source_target', ['sourceDrawingId', 'targetDrawingId'])
@Index('IDX_cross_ref_type', ['referenceType'])
export class DrawingCrossReference {
  /**
   * Unique identifier (UUID v4)
   */
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  // ==================== SOURCE DRAWING ====================

  /**
   * Source drawing ID (the one making the reference)
   */
  @Column('uuid')
  sourceDrawingId!: string;

  /**
   * Source drawing relation
   */
  @ManyToOne(() => Drawing, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'sourceDrawingId' })
  sourceDrawing!: Drawing;

  // ==================== TARGET DRAWING ====================

  /**
   * Target drawing ID (the one being referenced)
   */
  @Column('uuid')
  targetDrawingId!: string;

  /**
   * Target drawing relation
   */
  @ManyToOne(() => Drawing, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'targetDrawingId' })
  targetDrawing!: Drawing;

  // ==================== REFERENCE DETAILS ====================

  /**
   * Type of reference
   */
  @Column({
    type: 'enum',
    enum: ReferenceType,
    default: ReferenceType.OTHER,
  })
  referenceType!: ReferenceType;

  /**
   * Callout text/marker on drawing (e.g., "3/A-501", "DETAIL A")
   */
  @Column({ type: 'varchar', length: 100, nullable: true })
  calloutText!: string | null;

  /**
   * Reference description
   * E.g., "Wall section at exterior wall", "Foundation detail at column line A"
   */
  @Column({ type: 'text', nullable: true })
  description!: string | null;

  /**
   * Grid location where reference occurs on source drawing
   * E.g., "A1-B2", "Grid Line 5"
   */
  @Column({ type: 'varchar', length: 100, nullable: true })
  gridLocation!: string | null;

  /**
   * Sheet coordinates where callout appears (x, y in PDF/drawing units)
   * Useful for direct navigation in viewers
   */
  @Column({ type: 'jsonb', nullable: true })
  coordinates!: {
    x: number;
    y: number;
    page?: number;
  } | null;

  /**
   * Additional notes about the reference
   */
  @Column({ type: 'text', nullable: true })
  notes!: string | null;

  // ==================== METADATA ====================

  /**
   * Custom fields for project-specific data
   */
  @Column({ type: 'jsonb', default: {} })
  metadata!: Record<string, any>;

  /**
   * Is this an automatic/system-generated reference or manual?
   */
  @Column({ type: 'boolean', default: false })
  isAutoGenerated!: boolean;

  /**
   * Has this reference been verified by a user?
   */
  @Column({ type: 'boolean', default: false })
  isVerified!: boolean;

  /**
   * User who verified the reference (UUID)
   */
  @Column({ type: 'uuid', nullable: true })
  verifiedById!: string | null;

  /**
   * When reference was verified
   */
  @Column({ type: 'timestamp', nullable: true })
  verifiedAt!: Date | null;

  // ==================== AUDIT FIELDS ====================

  /**
   * When reference was created
   */
  @CreateDateColumn()
  createdAt!: Date;

  /**
   * User who created the reference (UUID)
   */
  @Column({ type: 'uuid', nullable: true })
  createdById!: string | null;
}
